### ISSUE TITLE
1

### ISSUE THREAD

**Issue by a571-op** [sjw821/wafer-map-active-learning#2]

**Comment by a571-op** [comment]
![Uploading image.png…]()

**Comment by a571-op** [comment]
![image](https://user-images.githubusercontent.com/76274232/112155862-afba5b00-8c20-11eb-8ca1-6faae3f21c7c.png)

**Comment by a571-op** [comment]
![image](https://user-images.githubusercontent.com/76274232/112156030-d7a9be80-8c20-11eb-82df-dd6b180dbd6e.png)

**Comment by sjw821** [comment]
Hi.
The version of the package I used is as follows.

python 3.7.4
tensorflow 1.14
pandas 0.25.1
numpy 1.17.2
pytorch 1.2

Thank you.

**Comment by a571-op** [comment]
Thank you very much for your reply. Once again, could you tell me if you have encountered this problem while running the code? I didn't make any changes to your code, but this problem occurred. Do you know what happened

**Comment by a571-op** [comment]
I will change my environment to the same as you, and still report this error. I have tried many methods, but they can't solve it. Can you help me?
